improved much the debugging
now using traceback module and sys.exc_info()
If now any (excepted, which should be in place in any api call) error occours, two lines are added to xbmc log (Loglevel NOTICE):
ERROR: <script-api-call>: <error>
TRACEBACK: <traceback>